### ISSUE TITLE
Add Elixir (and Erlang)

### ISSUE THREAD

**Issue by JEG2** [icfpcontest2020/dockerfiles#10]
Elixir requires Erlang, so this is a request for that language as well.  

The current version of Elixir is [1.10.3](https://elixir-lang.org/install.html).  The current version of Erlang is [OTP 23.0](https://www.erlang.org/downloads).

**Comment by beevee** [comment]
Thanks for the suggestion! Would you like to create a PR with your favorite and most convenient build tools for Elixir? I can make one, but it will probably be a very simple Hello world application compiled with the most basic command I can find in the Quickstart guide.

Please, use https://github.com/icfpcontest2020/dockerfiles/tree/master/dockerfiles/haskell as an example of file layout for base image and submission image.

**Comment by JEG2** [comment]
@piisalie, want to tackle this one?

**Comment by piisalie** [comment]
Sure @JEG2 

@beevee can you unpack what `Command line arguments will be provided to your program` means?

Do we have control over these command line arguments?  Or are those to be determined in context of the contest?

**Comment by piisalie** [comment]
Ask because Elixir/Erlang's release process is kind of odd, so knowing how exactly we expect the application to be started, and if we have control over the arguments passed at runtime would directly affect how I'd write an ideal Dockerfile.

**Comment by beevee** [comment]
Considering all the other proposals for different platforms, I think you should do this:

1. Use [C++ Dockerfile](https://github.com/icfpcontest2020/dockerfiles/blob/master/dockerfiles/cpp/Dockerfile) and [starterkit-cpp](https://github.com/icfpcontest2020/starterkit-cpp) as an example of build and run process. You will find `build` and `run` shell scripts that serve as extension points to pass any arguments you like during the build and run time.

2. Include all the necessary libraries for HTTP interaction and show a simple example of said interaction along the lines of [starterkit-csharp](https://github.com/icfpcontest2020/starterkit-csharp/blob/master/app/Program.cs). This should answer your question on purpose of command line arguments :-) Basically fetch URL that is passed as a first argument with a query parameter that is passed as a second argument. Exit with non-zero code on any non-200 status code returned.

**Comment by beevee** [comment]
I've created a starterkit repo for Elixir: https://github.com/icfpcontest2020/starterkit-elixir/

**Comment by piisalie** [comment]
Okay - thanks.  I'll give it a shot.

**Comment by beevee** [comment]
Well, it builds without errors. And when run it makes a HTTP request to the provided URL. I consider that a success. Thank you very much for the contribution!
