### ISSUE TITLE
Support Bazel

### ISSUE THREAD

**Issue by nya3jp** [icfpcontest2020/dockerfiles#12]
[Bazel](https://bazel.build/) is a language-agnostic build system. My team has been using the system to build C++ programs in recent ICFP contests ([2017](https://github.com/nya3jp/icfpc2017), [2018](https://github.com/nya3jp/icfpc2018), [2019](https://github.com/nya3jp/icfpc2019)). We'd like to use it in this year's contest as well.

However Bazel downloads some language toolchains during build for reproducibility. For example, on buliding Java programs, Bazel downloads OpenJDK of a fixed version. However [README](https://github.com/icfpcontest2020/dockerfiles#submission-mechanism) says there is no Internet access during build.

Could you give me guidance on how to proceed?

**Comment by beevee** [comment]
Can you create a base image with all necessary toolchains already downloaded? As suggested [here](https://github.com/icfpcontest2020/dockerfiles/issues/8#issuecomment-651310639).

**Comment by nya3jp** [comment]
Sure. I'm sending a PR.
