### ISSUE TITLE
Need C++ HTTP library

### ISSUE THREAD

**Issue by jeremysawicki** [icfpcontest2020/dockerfiles#23]
A library will be needed to talk to an HTTP server in C++.  There are likely many options.  One I have used is libcurl.  The development package (libcurl4-openssl-dev) is already available in the gcc:10.1.0 image, assuming the build process is enhanced to permit linking against a library (https://github.com/icfpcontest2020/dockerfiles/issues/20).  But the runtime package (libcurl4) is not available in the debian:buster-20200607-slim image, so the resulting binary will not run.

More generally, it will probably be necessary to create a customized base image as was done with haskell (https://github.com/icfpcontest2020/dockerfiles/issues/8) so packages needed/wanted by various teams can be installed.  Packages may need to be added to both the gcc:10.1.0 and debian:buster-20200607-slim images, so I supposed two customized images should be created.

**Comment by beevee** [comment]
We're currently in the process of improving starter kits to show an example of HTTP interaction. See [starterkit-csharp](https://github.com/icfpcontest2020/starterkit-csharp), for example. It will require us to add necessary libraries and resolve the issue that you mentioned.

We'll get to C++ eventually, but you can help if you have time.

**Comment by nya3jp** [comment]
FYI, I updated starterkit-bazel to use [CPR](https://github.com/whoshuu/cpr) as sn HTTP client library. 

I'm afraid I don't have enough CMake knowledge to help starterkit-cpp, sorry.

**Comment by beevee** [comment]
We've included a simple header-only HTTP library in our C++ starterkit: https://github.com/icfpcontest2020/starterkit-cpp/tree/master/app

Looking forward to a PR with a more proper dependency support.
