### ISSUE TITLE
Generic JVM image?

### ISSUE THREAD

**Issue by belyaev-mikhail** [icfpcontest2020/dockerfiles#33]
It is mentioned in other issues that the organizers are ok with pre-built binaries in the solutions.
This, however, does not help the jvm languages as the bash image does not include java.

Providing several images containing typical jvm build systems (maven/gradle/sbt/etc.) also makes little sense, as they all are built around having an internet connection which is disallowed during build. Furthermore, providing dependencies for e.g. maven without internet connection is pretty hard, non-trivial and ugly.

I hereby propose to include a jvm-generic image that accepts any `app.jar` as the program source and runs it (essentially the java image minus the actual javac invocation). This is essentially the same as "submitting pre-built binary" but for jvm.

**Comment by belyaev-mikhail** [comment]
I will work on a pull request for this myself if this is ok with the organizers.

**Comment by beevee** [comment]
I think, it would be better to just extend our current java image with `build` and `run` scripts. Something along the lines of [starterkit-cpp](https://github.com/icfpcontest2020/dockerfiles/blob/master/dockerfiles/cpp/Dockerfile). This way you can hide `javac` invocation inside `build` script and easily replace it with copying of a prebuilt jar.

**Comment by belyaev-mikhail** [comment]
Ok, this works, too

**Comment by beevee** [comment]
@belyaev-mikhail do you think current `java` platform covers your scenario?

https://github.com/icfpcontest2020/dockerfiles/tree/master/dockerfiles/java

**Comment by belyaev-mikhail** [comment]
Seems legit to me
