### ISSUE TITLE
Add R

### ISSUE THREAD

**Issue by gringer** [icfpcontest2020/dockerfiles#35]
My R solution got an implicit mention in last year's summary (as a team where I used the neural network of my partner and kids to help solve puzzles). It would be great to be able to use R again this time around.

Being able to use Shiny as well (for quickly designing UI that work as Web applications) would be extremely helpful:

https://hub.docker.com/r/rocker/shiny-verse/dockerfile

**Comment by gringer** [comment]
For what it's worth, there's an `Rscript` command that allows for command-line execution of R code. Here's an example that sends the result of running code to a file `output.txt`.
    Rscript main.r > output.txt

Assuming that [this CPP file](https://github.com/icfpcontest2020/starterkit-cpp/blob/master/app/main.cpp) represents what the code should do, I'll have a go at creating an R script that does this. I'd be something like this:

```
#!/usr/bin/env Rscript
library(dplyr, warn.conflicts=FALSE);
library(httr);
commandArgs(TRUE)[1] -> server_url;
commandArgs(TRUE)[2] -> player_key;
paste0("ServerUrl: ", server_url, "; PlayerKey: ", player_key, "\n") %>%
  cat();
server_url %>%
  get() -> res; # not sure if this will work directly; it's worth a try...
if(((nchar(content(res, as="text")) == 0)) || (http_status(res) != 200)){ # check html response code == 200
  quit(status=1);
}
quit(status=0);
```

**Comment by gringer** [comment]
My guess at a Dockerfile:

```
FROM rocker/shiny-verse:4.0.2

WORKDIR /solution
COPY ./build.sh .
COPY ./run.sh .
RUN chmod +x ./build.sh
RUN chmod +x ./run.sh
RUN ./build.sh
ENTRYPOINT ["./run.sh"]
```

Associated `build.sh` [R is an interpreted language]:

```
#!/bin/sh

echo "Build not required"
```

Associated `run.sh` [based on the javascript starterkit]:

```
#!/bin/sh

cd app
Rscript ./main.R "$@" || echo "run error code: $?"

```

**Comment by beevee** [comment]
Great success! It works with only a slight tweak or two. You are a hero! See https://github.com/icfpcontest2020/starterkit-r
