### ISSUE TITLE
Submissions: the bot does not see my test submission

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [icfpcontest2020/dockerfiles#45]
What I've done:
- [x] created a private Git repository
- [x] copied the deploy key and added it to the repository
- [x] created a branch called `submission`
- [x] downloaded a starter kit
- [x] committed and pushed the starter kit
- [x] waited for more than 10 minutes

The repository is `git@github.com:Vlad-Shcherbina/icfpc2020-tbd.git`.

### What went wrong

The submission checklist is in the following state:

    ✅ Create a private Git repository
    ✅ Register your team
    ---- YOU ARE HERE ---
    ☑️ Copy the deploy key and add it to your repository (?)
    ☑️ Create a branch called submission
    ☑️ Download a starter kit for your language of choice
    ☑️ If there's none, file an issue
    ☑️ Commit and push the starter kit to submission
    ☑️ Wait for your submission to appear below (<= 10 min)

No submission appears in the table.

GitHub shows that this deploy key was recently used, so apparently your bot is scraping the repository.

**Comment by spaceorc** [comment]
Out build system monitors new commits that came AFTER team has been successfully registered. Your repository is registered successfully, as I see, but you should make any new commit to the `submission` branch for our system to detect it.

**Comment by Vlad-Shcherbina** [comment]
Thank you. Indeed it picks up new commits just fine.
