### ISSUE TITLE
Submissions: test server reruns the same commit multiple times

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [icfpcontest2020/dockerfiles#49]
Repository URL: `git@github.com:Vlad-Shcherbina/icfpc2020-tbd.git`

The day before yesterday I submitted, among others, the commit `bd58c6`. Test server successfully ran it.
However, yesterday it ran it 7 more times without any action on my side.

Just letting you know.

**Comment by AndrewKostousov** [comment]
Yesterday around 17:30 UTC we had a glitch in our submission system (still being actively developed :-)) which triggered multiple builds for existing submissions. Shortly after problem was solved. Sorry for inconvenience.
