### ISSUE TITLE
Add Scala

### ISSUE THREAD

**Issue by TimoMeijer** [icfpcontest2020/dockerfiles#58]
Please consider adding this language or platform.

What can I do to support a PR with a Dockerfile and a starter kit?

**Comment by beevee** [comment]
Sure. Would you like to help?

We'll need to add dockerfiles to this repository (see https://github.com/icfpcontest2020/dockerfiles/tree/master/dockerfiles/java for example).

We'll also need to create a starterkit that does a HTTP POST request to the provided URL.
I've created a repo for Scala starterkit here: https://github.com/icfpcontest2020/starterkit-scala
You can use the Java starterkit as an example of the desired behavior: https://github.com/icfpcontest2020/starterkit-java

**Comment by beevee** [comment]
Hi @TimoMeijer! Need any help?

**Comment by TimoMeijer** [comment]
Hi @beevee, I think I'll be able to work from the java files to get something for Scala!

**Comment by beevee** [comment]
![image](https://user-images.githubusercontent.com/1009675/87672976-3747f400-c78d-11ea-8905-9fa2e2a2a8bc.png)
