### ISSUE TITLE
lost registration 8-)

### ISSUE THREAD

**Issue by win32asm** [icfpcontest2020/dockerfiles#59]
1) sorry for the disturbance,I logged out of the https://icfpcontest2020.github.io account without saving API key. However, I have set up the repository and (I hope) provided the correct email. Is there a way to restore the key? what information should I provide? Or I must register another team name?
2) to avoid such mistakes in future - would it make sense to add a line in big letters about saving the API key for further logins? 8-)
3) or is there a plan to send the critical access information to the registered email? I can't think of a way to avoid (ab)using the feature, but it could definitely help.

Thanks,
Vlad.

**Comment by igorlukanin** [comment]
Hi 👋 I've sent the API key to an email provided during the registration. Wish you a great contest.

Feel free to reopen this issue or reach out to me in any case.
