### ISSUE TITLE
Submissions page shows an HTTP 500 error

### ISSUE THREAD

**Issue by jmerle** [icfpcontest2020/dockerfiles#60]
What I've done:
- [x] created a private Git repository
- [x] copied the deploy key and added it to the repository
- [x] created a branch called `submission`
- [x] downloaded a starter kit
- [x] committed and pushed the starter kit
- [x] waited for more than 10 minutes

Here's the problem:

The submissions page shows "Something went wrong. Server answer is 500" as error message. I've seen it work about two hours ago with two submissions visible.

**Comment by spaceorc** [comment]
Oops... my fault. Will fix immediately.

**Comment by igorlukanin** [comment]
@jmerle Hope it's resolved now. Feel free to reopen this issue in any case!

**Comment by jmerle** [comment]
Yep, it's resolved, thanks!

I also noticed I accidentally leaked my API key in the first revision of the opening post of this issue, so I created a new team and abandoned the old one (the old team is now called "oops_leaked_my_api_key").

**Comment by igorlukanin** [comment]
@jmerle Thanks for mentioning that! Gonna disable that team.
