### ISSUE TITLE
Add TypeScript

### ISSUE THREAD

**Issue by rkirov** [icfpcontest2020/dockerfiles#62]
Please consider adding this language or platform.

It should be a small modification to starterkit-javascript to have build.sh run the TypeScript compiler.

**Comment by beevee** [comment]
Thanks for your suggestion!

Question is: do you need any dependencies other than `node` in your base image? If not, you can use the existing `javascript` platform and just write anything you like in the `run.sh` file of your submission.

**Comment by rkirov** [comment]
Node is enough indeed. I guess there is no need to build as part of the submission process, I can just build locally and submit the .js build artifacts as part of the existing JavaScript.

I just did what you suggested and that works fine.
