### ISSUE TITLE
Submissions: 

### ISSUE THREAD

**Issue by akesling** [icfpcontest2020/dockerfiles#72]
What I've done:
- [*] created a private Git repository
- [*] copied the deploy key and added it to the repository
- [*] created a branch called `submission`
- [*] downloaded a starter kit
- [*] committed and pushed the starter kit
- [*] waited for more than 10 minutes

Here's the problem:

I got the initial `submission` branch working but wanted to test the `submissions/*` style so my team mates and I can submit various directions without stepping on each other's toes.  I pushed `submissions/starter` as an exact copy of the `submission` branch that previously worked (as well as trying a number of other non-identical branches) and none of them (except the original) have shown up on the submissions page.  This is for team **OMG ICFP FTW**.

What might I be doing wrong?

**Comment by spaceorc** [comment]
Moment, I should have a look

**Comment by spaceorc** [comment]
You have deleted the main `submission` branch from your repository. This branch is mandatory, others are optional.

**Comment by akesling** [comment]
Huh... alright.  Could you make that clear in the docs?  I have a sneaking suspicion someone else might run into this same issue :P.

I've pushed a new `submission` branch and it seems to have picked up at least one of the changes.  Is there any way to know *which* branch a given submission came from?

**Comment by spaceorc** [comment]
Yes, we will update the docs.
The very first column in submissions list is commit hash - maybe it can help you.
Adding branch to this list is good idea, thanks! We will think about it.

**Comment by akesling** [comment]
> The very first column in submissions list is commit hash - maybe it can help you.
Yeah, that's doable but a bit awkward.

> Adding branch to this list is good idea, thanks! We will think about it.
It would be appreciated 👍 .

Thank you for your time.
