### ISSUE TITLE
Add Prolog

### ISSUE THREAD

**Issue by gringer** [icfpcontest2020/dockerfiles#81]
Please consider adding this language or platform.

As per [this tweet](https://twitter.com/madeofmistak3/status/1283426580363005952)

I might possibly send a PR with a Dockerfile and a starter kit.... or just dump the files into this issue, as I did for R, because I can't get my head around how to submit a pull request that works properly.

**Comment by gringer** [comment]
The beginnings of `app/start.pl`:

```
#!/usr/bin/env swipl

use_module(library(http/http_client)).

http_get("http://www.gringene.org", X, [status_code(Y)]).

```

Note: The above doesn't work yet.

**Comment by igorlukanin** [comment]
We've added this platform and a starter kit as you suggested. Enjoy!

Feel free to reopen the issue in any case.
