### ISSUE TITLE
Submissions:

### ISSUE THREAD

**Issue by GeePokey** [icfpcontest2020/dockerfiles#82]
What I've done:
- [*] created a private Git repository
- [*] copied the deploy key and added it to the repository
- [*] created a branch called `submission`
- [*] downloaded a starter kit
- [*] committed and pushed the starter kit
- [*] waited for more than 10 minutes

Here's the problem:
Cannot find revision of the default branch 'refs/heads/submission' of vcs root 'jetbrains.git'

first time through I lost the .dot files from the starter kit, but then I read about needing .platform and I committed/pushed .platform to my submission branch.  Still same issue on submission log.
I did add the deploy key.

[WHAT WENT WRONG]
my repo:  https://github.com/GeePokey/Canivsar2020

**Comment by beevee** [comment]
Can you please tell me the team name?

**Comment by GeePokey** [comment]
Canivsar

**Comment by spaceorc** [comment]
As I see there is no 'submission' branch in git repo you entered.
And it is not https://github.com/GeePokey/Canivsar2020. It is another: git@github.com:GeePokey/MoonBaseAlpha.git

**Comment by GeePokey** [comment]
I believe that the repository you've specified in your team profile is different from what you've sent above :)
After you change the repo, please push a new commit to trigger the submission
12:39 AM
got it - okay - thanks I'm winning now!  This was pretty close to did I actually plug in the computer :P
thanks for the help
