### ISSUE TITLE
Add Kotlin

### ISSUE THREAD

**Issue by 0legg** [icfpcontest2020/dockerfiles#9]
Kotlin is the [4th loved](https://insights.stackoverflow.com/survey/2020#technology-most-loved-dreaded-and-wanted-languages-loved) and [6th wanted](https://insights.stackoverflow.com/survey/2020#technology-most-loved-dreaded-and-wanted-languages-wanted) programming language, according to StackOverflow survey.

**Comment by beevee** [comment]
Thanks for the suggestion! Would you like to create a PR with your favorite and most convenient build tools for Kotlin? I can make one, but it will probably be a very simple `Hello world` application compiled with the most basic command I can find in the Quickstart guide.
